actor:
  draft:
    system_instructions: './data/patterns/actor_critic/actor/draft/system_instructions.txt'
    user_instructions: './data/patterns/actor_critic/actor/draft/user_instructions.txt'
    response_schema: './data/patterns/actor_critic/actor/draft/response_schema.json'
  revise:
    system_instructions: './data/patterns/actor_critic/actor/revise/system_instructions.txt'
    user_instructions: './data/patterns/actor_critic/actor/revise/user_instructions.txt'
    response_schema: './data/patterns/actor_critic/actor/revise/response_schema.json'

critic:
  review:
    system_instructions: './data/patterns/actor_critic/critic/review/system_instructions.txt'
    user_instructions: './data/patterns/actor_critic/critic/review/user_instructions.txt'
    response_schema: './data/patterns/actor_critic/critic/review/response_schema.json'
  revise:
    system_instructions: './data/patterns/actor_critic/critic/revise/system_instructions.txt'
    user_instructions: './data/patterns/actor_critic/critic/revise/user_instructions.txt'
    response_schema: './data/patterns/actor_critic/critic/revise/response_schema.json'