coordinator:
  travel_planner:
    system_instructions: './data/patterns/actor_critic/actor/draft/system_instructions.txt'
    user_instructions: './data/patterns/actor_critic/actor/draft/user_instructions.txt'
    response_schema: './data/patterns/actor_critic/actor/draft/response_schema.json'
delegate:
  flight_search:
    system_instructions: './data/patterns/actor_critic/actor/draft/system_instructions.txt'
    user_instructions: './data/patterns/actor_critic/actor/draft/user_instructions.txt'
  hotel_search:
    system_instructions: './data/patterns/actor_critic/actor/draft/system_instructions.txt'
    user_instructions: './data/patterns/actor_critic/actor/draft/user_instructions.txt'
  car_rental_search:
  system_instructions: './data/patterns/actor_critic/actor/draft/system_instructions.txt'
  user_instructions: './data/patterns/actor_critic/actor/draft/user_instructions.txt'
