coordinator:
  ner:
    system_instructions: './data/patterns/parallel_delegates/coordinator/ner/system_instructions.txt'
    user_instructions: './data/patterns/parallel_delegates/coordinator/ner/user_instructions.txt'
    response_schema: './data/patterns/parallel_delegates/coordinator/ner/response_schema.json'
  consolidate:
    system_instructions: './data/patterns/parallel_delegates/coordinator/consolidate/system_instructions.txt'
    user_instructions: './data/patterns/parallel_delegates/coordinator/consolidate/user_instructions.txt'
delegate:
  flight_search:
    system_instructions: './data/patterns/parallel_delegates/delegate/flight_search/system_instructions.txt'
    user_instructions: './data/patterns/parallel_delegates/delegate/flight_search/user_instructions.txt'
    response_schema: './data/patterns/parallel_delegates/delegate/flight_search/response_schema.json'
  hotel_search:
    system_instructions: './data/patterns/parallel_delegates/delegate/hotel_search/system_instructions.txt'
    user_instructions: './data/patterns/parallel_delegates/delegate/hotel_search/user_instructions.txt'
    response_schema: './data/patterns/parallel_delegates/delegate/hotel_search/response_schema.json'
  car_rental_search:
    system_instructions: './data/patterns/parallel_delegates/delegate/car_rental_search/system_instructions.txt'
    user_instructions: './data/patterns/parallel_delegates/delegate/car_rental_search/user_instructions.txt'
    response_schema: './data/patterns/parallel_delegates/delegate/car_rental_search/response_schema.json'
